### ISSUE TITLE
Home View 개발

### ISSUE THREAD

**Issue by 2Jaeheon** [2Jaeheon/movie-app#16]
## 📄 설명
프로젝트의 홈 화면에서 보이는 메인 화면을 개발합니다.

## ✔️ To-Do
- [x] Home VIew 레이아웃 
- [x] 홈 뷰 모달
- [x] 유튜브 영상 볼 수 있도록 구현
- [x] 페이지 디자인

## ✍️ 기타
- [x] 반응형으로 모바일에서도 잘 보이도록 합니다.
- [x] 모달에서 유튜브 동영상이 재생되도록 합니다
