### ISSUE TITLE
SearchView 

### ISSUE THREAD

**Issue by 2Jaeheon** [2Jaeheon/movie-app#20]
## 📄 설명
검색 창을 구현합니다. 

## ✔️ To-Do
- [x] 필터와 검색 두 개중 하나로 접속해서 기능 사용
- [x] 필터에 다양한 기능 추가(국가, 장르 등)
- [x] 검색시 자동으로 영화 데이터 보여지도록 구현
