### ISSUE TITLE
react-router-dom을 이용한 라우팅 설정

### ISSUE THREAD

**Issue by 2Jaeheon** [2Jaeheon/movie-app#8]
## 📄 설명
라우팅을 설정하기 위해 React Router를 설치하고 
AppRoutes.tsx에서 BrowserRouter, Routes, Route를 사용하여 Home, Search, Wishlist 경로를 설정합니다.

## ✔️ To-Do
- [x] Home Routing 설정
- [x] Search Routing 설정
- [x] Wishlist Routing 설정
- [x] App.tsx에서 AppRoutes 사용해서 라우팅을 적용

## ✍️ 기타
기본적인 라우팅 설정입니다.
